version: '3.1'

services:
  app:
    container_name: app
    image: test-docker/node-web-app
    # docker compose will create a network, add network_mode: bridge to connect db
    network_mode: bridge
    # build: .
    depends_on:
      - db
    ports:
      - 8082:3000
    environment:
      - DB_TYPE=postgres
      - DB_PORT=5432
      - DB_DATABASE=nestjs-base
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=Bao123456.
      - DB_SYNCHRONIZE=false
    # need to link to db when use DB_HOST=db 
    links:
      - db  
  db:
    container_name: postgres
    image: postgres
    network_mode: bridge
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Bao123456.
      - POSTGRES_DB=nestjs-base

# create container ubuntu with nodejs, not run in lastest version ubuntu image
# version: '3.1'
# services:
#   ubuntu:
#     container_name: ubuntu
#     image: ubuntu:14.04
#     tty: true
#     ports:
#       - 8082:3000
#     restart: always
#     command: sh -c "
#       apt-get update && 
#       apt-get upgrade -y && 
#       apt-get install -y curl && 
#       curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && 
#       apt-get install -y nodejs --force-yes
#       "
        